# fly.toml app configuration file generated for hourtrack-dark-water-4176 on 2025-02-02T11:42:52-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hourtrack-dark-water-4176'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[mounts]
  source="db_data"
  destination="/data"
  
[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
